### ISSUE TITLE
name 'ex' is not defined

### ISSUE THREAD

**Issue by chandra-siri** [arunbalajeev/query-video-summary#1]
@arunbalajeev 
while runnning this cell in summarization_demo. I'm getting the following error. 

from qvsumm.shells import *
K=5 ### Number of elements in the summary
S1=qvsumm.shells.Summ(query,imagenames,relscores,intscores)
S1.budget=K
objectives=[quality_shell(S1),similarity_shell(S1),diversity_shell(S1),ex.representativeness_shell(S1)]
weights=[0.00963344,  0.45267703,  0.43680236,  0.10088718 ]###weights for the objectives
selected_elements,score,_=gm_submodular.lazy_greedy_maximize(S1,weights,objectives,budget=K,randomize=True)

NameError                                 Traceback (most recent call last)
<ipython-input-8-26b0326316d7> in <module>()
      8 S1=qvsumm.shells.Summ(query,imagenames,relscores,intscores)
      9 S1.budget=K
---> 10 objectives=[quality_shell(S1),similarity_shell(S1),diversity_shell(S1),ex.representativeness_shell(S1)]
     11 weights=[0.00963344,  0.45267703,  0.43680236,  0.10088718 ]###weights for the objectives
     12 selected_elements,score,_=gm_submodular.lazy_greedy_maximize(S1,weights,objectives,budget=K,randomize=True)

NameError: name 'ex' is not defined

I tried to debug but couldn't find it. could you please let me know what's happening ?

**Comment by arunbalajeev** [comment]
ex---> objectives used in gm_submodular module.
Added the definition now in shells.py
Could you please check now?

**Comment by chandra-siri** [comment]
yeah it's working. Thanks @arunbalajeev
